import * as fs from 'fs';
import * as path from 'path';
import axios from 'axios';
import * as dotenv from 'dotenv';
import { MeetingMinutes } from './ai';

dotenv.config();

export async function exportToMarkdown(
  minutes: MeetingMinutes,
  outputPath: string
): Promise<string> {
  const markdown = generateMarkdown(minutes);

  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, markdown, 'utf-8');
  return outputPath;
}

function generateMarkdown(minutes: MeetingMinutes): string {
  const date = new Date(minutes.date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let md = `# ${minutes.title}\n\n`;
  md += `**Date:** ${date}\n\n`;

  if (minutes.participants && minutes.participants.length > 0) {
    md += `**Participants:** ${minutes.participants.join(', ')}\n\n`;
  }

  md += `## Summary\n\n${minutes.summary}\n\n`;

  if (minutes.keyPoints.length > 0) {
    md += `## Key Discussion Points\n\n`;
    minutes.keyPoints.forEach((point) => {
      md += `- ${point}\n`;
    });
    md += '\n';
  }

  if (minutes.decisions.length > 0) {
    md += `## Decisions Made\n\n`;
    minutes.decisions.forEach((decision) => {
      md += `- ${decision}\n`;
    });
    md += '\n';
  }

  if (minutes.actionItems.length > 0) {
    md += `## Action Items\n\n`;
    minutes.actionItems.forEach((item) => {
      md += `- [ ] ${item}\n`;
    });
    md += '\n';
  }

  md += `---\n\n`;
  md += `*Generated by [MeetingMinutes](https://github.com/ranjan98/meeting-minutes)*\n`;

  return md;
}

export async function exportToSlack(minutes: MeetingMinutes): Promise<void> {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;

  if (!webhookUrl) {
    throw new Error('SLACK_WEBHOOK_URL not configured in .env');
  }

  const blocks = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: minutes.title,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Summary:*\n${minutes.summary}`,
      },
    },
  ];

  if (minutes.keyPoints.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Key Points:*\n${minutes.keyPoints.map((p) => `• ${p}`).join('\n')}`,
      },
    });
  }

  if (minutes.actionItems.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Action Items:*\n${minutes.actionItems.map((a) => `☐ ${a}`).join('\n')}`,
      },
    });
  }

  await axios.post(webhookUrl, { blocks });
}

export async function exportToNotion(minutes: MeetingMinutes): Promise<string> {
  const notionToken = process.env.NOTION_TOKEN;
  const databaseId = process.env.NOTION_DATABASE_ID;

  if (!notionToken || !databaseId) {
    throw new Error('NOTION_TOKEN and NOTION_DATABASE_ID required in .env');
  }

  const response = await axios.post(
    'https://api.notion.com/v1/pages',
    {
      parent: { database_id: databaseId },
      properties: {
        Name: {
          title: [
            {
              text: {
                content: minutes.title,
              },
            },
          ],
        },
        Date: {
          date: {
            start: new Date(minutes.date).toISOString().split('T')[0],
          },
        },
      },
      children: [
        {
          object: 'block',
          type: 'heading_2',
          heading_2: {
            rich_text: [{ type: 'text', text: { content: 'Summary' } }],
          },
        },
        {
          object: 'block',
          type: 'paragraph',
          paragraph: {
            rich_text: [{ type: 'text', text: { content: minutes.summary } }],
          },
        },
      ],
    },
    {
      headers: {
        Authorization: `Bearer ${notionToken}`,
        'Notion-Version': '2022-06-28',
        'Content-Type': 'application/json',
      },
    }
  );

  return response.data.url;
}
